name       : kguiaddons
version    : 5.84.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kguiaddons-5.84.0.tar.xz : 2924e91c79a91c8f2714c5f75c13c269cc95595d028d8e3613dba142ebef285d
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-3.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
