name       : kguiaddons
version    : 5.74.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kguiaddons-5.74.0.tar.xz : bb7c5b88e1738b22571f2f135202b3c08230911fcb8d089b8676d4d59af4578b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
