name       : kguiaddons
version    : 5.64.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kguiaddons-5.64.0.tar.xz : 4caac79b7341c7796f3ca5e1d88cef57ecab2eefcac9ab654fd977706c89bae4
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
