name       : kguiaddons
version    : 5.52.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kguiaddons-5.52.0.tar.xz : 6bda17a5252a627607a1110510676435772dcf27e2ca8486b7e5a1a56844c254
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
