name       : kguiaddons
version    : 5.72.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kguiaddons-5.72.0.tar.xz : a269c76390ff391613cd9030c4fafb85421145cb95dd784c63a2421595bc3b37
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
