name       : kguiaddons
version    : 5.53.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/kguiaddons-5.53.0.tar.xz : e6f8e20b128486aebd8b77915cd6d98ad33df791d9d1ea00c896627af09641ce
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
