name       : kguiaddons
version    : 5.54.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kguiaddons-5.54.0.tar.xz : 6524990f6df7db84ecb7f13250085ab9ce12fa43b2c47e81018755d9b0ee7852
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
