name       : kguiaddons
version    : 5.58.0
release    : 28
source     :
    - https://download.kde.org/stable/frameworks/5.58/kguiaddons-5.58.0.tar.xz : d6d5884f31072fe93804ecad72c8f612fa03d6841318211ad8f6ebf1f5f020f3
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
