name       : kguiaddons
version    : 5.75.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kguiaddons-5.75.0.tar.xz : 58aba1bd986020f7b4bde0d35a7b09730716cbdffde734e6d29cc9d18500253b
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
