name       : kguiaddons
version    : 5.49.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kguiaddons-5.49.0.tar.xz : b393163c4ca80f08126d9601e70d2a705fdb157e6dd1c4188d7bfb5be86872fe
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
