name       : kguiaddons
version    : 5.56.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kguiaddons-5.56.0.tar.xz : b190b601679bb5f6994f85d452b0a182283dbb872b688447449aefe09388e23e
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
