name       : kguiaddons
version    : 5.107.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/kguiaddons-5.107.0.tar.xz : ad2f6e6ca7dd3c230de54bab357e33a9c21e85a2836f63565e3b77ebf79984c1
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-3.0-only
    - LGPL-2.0-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
