name       : kguiaddons
version    : 5.44.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kguiaddons-5.44.0.tar.xz : ace931f71cb7cf688c3ac0504b2eae129b4f0571dbd2ed2b8b9ac6335714f4da
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming.tools
optimize   : lto
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
