name       : kguiaddons
version    : 5.55.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kguiaddons-5.55.0.tar.xz : 039a0f98b5491668ea4e2e45ca57c68bd5fea956f46ba50778283a8137e412a4
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
