name       : kguiaddons
version    : 5.79.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kguiaddons-5.79.0.tar.xz : bc00488e123a1f7905682393b140b80c8340cb131cc0baa3fb6ad575878f1c85
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
