name       : kguiaddons
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kguiaddons-5.66.0.tar.xz : 379e5ed87b00d344a13e424e39d97d74d494c503400bcd72df132de74c8cc591
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
