name       : kguiaddons
version    : 5.63.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/kguiaddons-5.63.0.tar.xz : b91ad511bbdacc60c1a41104011492d71a5116483dcccf1390c075fcb29a424c
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
