name       : kguiaddons
version    : 5.57.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kguiaddons-5.57.0.tar.xz : 744eb0ec35c936c17c3d11a08d19014e2166c4a307370207e0f5a38f01a91ebd
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
