name       : kguiaddons
version    : 5.67.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kguiaddons-5.67.0.tar.xz : 194c83258eddbc564b7cf41efb7e327fef1e5ed2ef2f348f962b8561f237fe08
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
