name       : kguiaddons
version    : 5.60.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kguiaddons-5.60.0.tar.xz : 228dc1715a35979072381658ca244795e989ea941e703559de398fdea793c548
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
