name       : kguiaddons
version    : 5.59.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kguiaddons-5.59.0.tar.xz : 63fcffb06e0c55d44f7c89c6f5052919e39d50412359b783bd9ff861478c8dc6
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
