name       : kguiaddons
version    : 5.76.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kguiaddons-5.76.0.tar.xz : bdaa2ed104bfa9c2ebd702f033935a83560e1d00c7302620a6ae52cb309c7125
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
