name       : kguiaddons
version    : 5.71.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kguiaddons-5.71.0.tar.xz : c1f7bf540a689319962275916c0434f47ba5ed8f7d46a78704393163e32eccd2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Utilities for graphical user interfaces.
description: |
    Utilities for graphical user interfaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
